Features/delete and update run
FabianMariusLink/vite pull request #10
Opened 2023-12-05 16:44 UTC by FabianMariusLink

Set up in backend: 
features deleteRunById and updateRun in … 
- RouteController
- RouteService
- Associated unit and integration tests

Set up in frontend:
- delete function on PageDetailsRun
- PageUpdateRun 
- few minor adjustments, such as relocating fetch method and few CSS changes

2023-12-06 08:11 UTC, MoinMarcell requested changes
Code sieht super aus, aber du hast 12% Code Duplication im Frontend;-)

2023-12-06 11:49 UTC, FabianMariusLink commented
@MoinMarcell Vielen Dank Dir für den Hinweis. Die Duplikate habe ich entfernt.

2023-12-07 09:17 UTC, mpagels approved these changes

2023-12-07 09:19 UTC, mpagels approved these changes

2023-12-07 09:39 UTC, MoinMarcell approved these changes
lgtm:)

2023-12-07 09:41 UTC, merged