Feature/add route
FabianMariusLink/vite pull request #7
Opened 2023-11-26 15:55 UTC by FabianMariusLink

Create in backend:
- Route model
- RouteDTO
- RouteController
- RouteService
- RouteRepository 
- Associated unit and integration tests
Create in Frontend:
- Component Header
- PageAddRoute

2023-11-27 12:49 UTC, MoinMarcell requested changes
Sieht soweit schon ganz gut aus! Habe ein paar Anmerkungen :-) Auch solltest du deine Codesmells checken und deine package-lock.json mal checken, da du 2 hast

2023-11-27 12:49 UTC, MoinMarcell commented on backend/package.json
> +{}
Was denn hier los?

2023-11-27 12:49 UTC, MoinMarcell commented on backend/src/main/java/com/github/fabianmariuslink/vite/route/Route.java
Das soll wahrscheinlich in der Db gespeichert werden oder? Dann fehlt ihr noch eine bestimmte Annotation für Mongo;-)

2023-11-27 12:49 UTC, MoinMarcell commented on backend/src/main/java/com/github/fabianmariuslink/vite/route/RouteService.java
> +                .id(null)
beim Builder nicht nötig. Attribute die nicht mit angegeben werden, werden mit null initialisiert, automatisch :-)

2023-11-27 12:49 UTC, MoinMarcell commented on backend/src/test/java/com/github/fabianmariuslink/vite/route/RouteControllerTest.java
> +        assertNotNull(savedRoute.description());
hier könntest du auch auf equals checken und mit savedRoute mit routeDetails vergleichen

2023-11-27 12:49 UTC, MoinMarcell commented on frontend/src/App.tsx
> +            <Route path="/PageAddRoute" element={<PageAddRoute/>}/>
```suggestion
            <Route path="/add-route" element={<PageAddRoute/>}/>
```

"PageAddRoute" ist keine gute Namensgebung für einen Pfad. Auch werden längere Pfade immer mit einem Minus getrennt :-)

2023-11-27 12:49 UTC, MoinMarcell commented on backend/src/test/resources/application.properties
> +de.flapdoodle.mongodb.embedded.version=6.0.1
```suggestion
de.flapdoodle.mongodb.embedded.version=7.0.0
```

2023-11-27 16:12 UTC, FabianMariusLink commented on backend/src/main/java/com/github/fabianmariuslink/vite/route/Route.java
Annotation wurde hinzugefügt.

2023-11-27 16:23 UTC, FabianMariusLink commented
@MoinMarcell Hallo Marcell, die Code Smells sollten behoben sein. Die Anmerkungen wurden alle umgesetzt. Vielen Dank Dir für die Anmerkungen.

2023-11-28 10:01 UTC, MoinMarcell approved these changes
lgtm!:)

2023-11-28 11:11 UTC, merged